SET NAMES utf8;
INSERT INTO SERVICE_PLAN(SERVICE_NAME, MONEY, PAY_DATE, REMARK) VALUES('月套餐', 50, 30, '50元使用1个月，优惠大酬宾');
INSERT INTO SERVICE_PLAN(SERVICE_NAME, MONEY, PAY_DATE, REMARK) VALUES('季套餐', 120, 90, '120元使用3个月，优惠大酬宾');

INSERT INTO USER_INFO(USER_NAME, USER_PASSWORD, REGISTER_DATE, EXPIRE_DATE, EMAIL, COMPANY, PHONE, LAST_PAY_DATE, SERVICE_PLAN_ID, QUESTION, ANSWER) 
VALUES('admin', MD5('admin'), now(), DATE_ADD(now(),INTERVAL 10 DAY), 'chen.guan@hp.com', 'HP', '13564793256', now(), 1, 'What is your name', 'Tom Guan');

INSERT INTO USER_INFO(USER_NAME, USER_PASSWORD, REGISTER_DATE, EXPIRE_DATE, EMAIL, COMPANY, PHONE, LAST_PAY_DATE, SERVICE_PLAN_ID, QUESTION, ANSWER) 
VALUES('123456', MD5('123456'), now(), DATE_ADD(now(),INTERVAL 10 DAY), 'chen.guan@hp.com', 'HP', '13564793256', now(), 2, 'What is your name', 'Tom Guan');

INSERT INTO USER_INFO(USER_NAME, USER_PASSWORD, REGISTER_DATE, EXPIRE_DATE, EMAIL, COMPANY, PHONE, LAST_PAY_DATE, SERVICE_PLAN_ID, QUESTION, ANSWER) 
VALUES('xxg2', MD5('xxg2'), now(), DATE_ADD(now(),INTERVAL 10 DAY), 'chen.guan@hp.com', 'HP', '13564793256', now(), 1, 'What is your name', 'Tom Guan');

INSERT INTO USER_INFO(USER_NAME, USER_PASSWORD, REGISTER_DATE, EXPIRE_DATE, EMAIL, COMPANY, PHONE, LAST_PAY_DATE, SERVICE_PLAN_ID, QUESTION, ANSWER) 
VALUES('tom', MD5('tom'), now(), DATE_ADD(now(),INTERVAL 10 DAY), 'chen.guan@hp.com', 'HP', '13564793256', now(), 2, 'What is your name', 'Tom Guan');

INSERT INTO USER_INFO(USER_NAME, USER_PASSWORD, REGISTER_DATE, EXPIRE_DATE, EMAIL, COMPANY, PHONE, LAST_PAY_DATE, SERVICE_PLAN_ID, QUESTION, ANSWER) 
VALUES('yangzuo', MD5('yangzuo'), now(), DATE_ADD(now(),INTERVAL 20 DAY), 'zuo.yang@163.com', 'HP', '13564793256', now(), 2, 'What is your name', 'Tom Guan');

INSERT INTO EXPENSE_RECORD(USER_INFO_ID, MONEY, PAY_DATE, EXPIRE_DATE) VALUES(1, '200', now(), now());
INSERT INTO EXPENSE_RECORD(USER_INFO_ID, MONEY, PAY_DATE, EXPIRE_DATE) VALUES(2, '200', now(), now());
INSERT INTO EXPENSE_RECORD(USER_INFO_ID, MONEY, PAY_DATE, EXPIRE_DATE) VALUES(2, '100', now(), now());
